# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9c0ebaaf8ee4e15e6c41ab073b62a26213c9fd250d2e8fb0324cc4418a5f5ccca155c9f7dab7d36280f332e381e9bde88adfec09d95bcb7d039b65308d74d97

test:
  secret_key_base: 433b5eb06eecafef0750f075ace02dbe024282e692f3f7e4115e1e3823999d2c6a2a3ec3c70375e72451e06720abf8ee89ff3fd63ac43325a53a3245efa7b964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
